title: Title
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon-isomer.ico

# Site colors
colors:
  primary-color: '#71B548'
  secondary-color: '#71B548'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'

# Info Sections
info-sections:
  - section-title: 
    section-subtitle: "Good hygiene. Together."
    section-description: |
      Practise the 7 Habits of Good Public Hyigene
      
      Lorem ipsum.
    section-more-button: More Information
    external: false
    section-more-button-url: /exhibitions/current-exhibitions/onpaper#tab1
    section-image-path: /images/event-images/onpaper/OnPaper-homepage-side-info.png

collections:
  join:
    output: true
  certified-premises:
    output: true
  resources:
    output: true
resources_name: media

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

